### ISSUE TITLE
Cant set download folder to anything that /var/lib/docker/*

### ISSUE THREAD

**Issue by geotmt1** [kokmok/rpi-nicotine-novnc#1]
I cant set my folder locations on something different that the mentioned location. Symlinks dont work as a fix and I cant seem to find any fix for this.
Heres the structure of the environment that was set up on my pi.

root@raspberrypi:/var/lib/docker/overlay2/7b7611c1b3251c0d62dc7e68731a0feb2c6a8bc1acedff87a44b2e61adc4d399/merged# ls -la
total 100
drwxr-xr-x 1 root root 4096 Mar 30 18:08 .
drwx------ 5 root root 4096 Mar 30 14:33 ..
drwxr-xr-x 1 root root 4096 Jan 14 11:00 bin
drwxr-xr-x 2 root root 4096 Jan  7  2015 boot
drwxr-xr-x 1 root root 4096 Mar 30 14:33 dev
-rwxr-xr-x 1 root root    0 Mar 30 14:33 .dockerenv
drwxr-xr-x 1 root root 4096 Mar 30 14:33 etc
drwxr-xr-x 3 root root 4096 Mar 30 18:02 home
-rwxr-xr-x 1 root root  800 Jan 14 10:42 init.sh
drwxr-xr-x 1 root root 4096 Oct 24 11:03 lib
drwxr-xr-x 1 root root 4096 Mar 30 18:00 media
drwxr-xr-x 3 root root 4096 Mar 30 18:08 mnt
drwxr-xr-x 2 root root 4096 Oct 24 11:03 opt
drwxr-xr-x 2 root root 4096 Oct 24 11:08 proc
drwx------ 1 root root 4096 Mar 30 17:51 root
drwxr-xr-x 1 root root 4096 Jan 14 10:54 run
drwxr-xr-x 1 root root 4096 Jan 14 11:00 sbin
drwxr-xr-x 2 root root 4096 Oct 24 11:03 srv
-rw-r--r-- 1 root root 2323 Mar 31 23:48 supervisord.log
-rw-r--r-- 1 root root    2 Mar 30 14:33 supervisord.pid
drwxr-xr-x 2 root root 4096 Apr 12  2015 sys
drwxrwxrwt 1 root root 4096 Mar 30 14:33 tmp
drwxr-xr-x 1 root root 4096 Jan 14 11:06 usr
drwxr-xr-x 1 root root 4096 Oct 24 11:03 var

My Downloads and Share Folder are set up on ./mnt/* and my incomplete files are on ./home/*

**Comment by kokmok** [comment]
How did you run the container (Could you please provide the command) ?
Also could you make this set of commands and post the result ?
`sudo docker ps`
copy the kokmok/rpi-nicotine-novnc:latest's container ID
`sudo docker inspect -f "{{ .Mounts }}" containerID`

**Comment by geotmt1** [comment]
How I started my docker:
sudo docker run -d --name nicotine --restart=always -v "/home/pi/.nicotine":"/root/.nicotine" -v "/mnt/usbhdd/Music/Soulseek":"/root/nicotine_downloads" -v "/mnt/usbhdd/Music":"/root/nicotine_uploads" -e resolution=1600x900 -p 6080:6080 kokmok/rpi-nicotine-novnc:latest

sudo docker ps
CONTAINER ID        IMAGE                              COMMAND                 CREATED             STATUS              PORTS                    NAMES
66ad1e9ad411        kokmok/rpi-nicotine-novnc:latest   "/bin/sh -c /init.sh"   43 hours ago        Up 43 hours         0.0.0.0:6080->6080/tcp   nicotine

sudo docker inspect -f "{{ .Mounts }}" 66ad1e9ad411
[{bind  /home/pi/.nicotine /root/.nicotine   true rprivate} {bind  /mnt/usbhdd/Music/Soulseek /root/nicotine_downloads   true rprivate} {bind  /mnt/usbhdd/Music /root/nicotine_uploads   true rprivate} {volume caf6f099ed086952860cca107cc68cdce16359eb7caeff9ab1310fa65b8332d7 /var/lib/docker/volumes/caf6f099ed086952860cca107cc68cdce16359eb7caeff9ab1310fa65b8332d7/_data /sys/fs/cgroup local  true }]

**Comment by kokmok** [comment]
ok everything seems to be ok.
could you please send the first line of `ls -la  /mnt/usbhdd/Music/Soulseek` (the on with single dot).
How did you mount the usb drive ?

**Comment by geotmt1** [comment]
drwxrwxr-x 1 pi pi     0 Mar 22 12:20  .
I dont remember. I just plugged my sata to usb into my hdd and pi and mounted it. Used a tutorial like this for the mount https://pimylifeup.com/raspberry-pi-mount-usb-drive/

**Comment by kokmok** [comment]
So when you download a file with your nicotine, it doesn't go to `/mnt/usbhdd/Music/Soulseek` ?
What are the parameters in your nicotine ? 
https://doc.ubuntu-fr.org/_media/nicotine/nicotine_plus_karmic_02.png?cache=&w=709&h=577&tok=4951cd

(sorry can't find the screenshot in english, but that's where you set the download folder) You have to set the download folder to `/root/nicotine_downloads`

**Comment by geotmt1** [comment]
![image](https://user-images.githubusercontent.com/44361518/55314160-32651100-5472-11e9-83e2-f7a06dcd160f.png)
it goes to:
/var/lib/docker/overlay2/7b7611c1b3251c0d62dc7e68731a0feb2c6a8bc1acedff87a44b2e61adc4d399/merged/mnt/usbhdd/Music/Soulseek

**Comment by kokmok** [comment]
Not this param. The ones under `Transfert->downloads` (sorry can't access my instance from here)

**Comment by geotmt1** [comment]
![image](https://user-images.githubusercontent.com/44361518/55314700-5ffe8a00-5473-11e9-954a-5457e454cc01.png)

**Comment by kokmok** [comment]
ok, set your download folder to `/root/nicotine_downloads`. It is binded to your `/mnt/Music` folder.
That's what i explained on the last line here : https://hub.docker.com/r/kokmok/rpi-nicotine-novnc/
But I probably should explain better :)

**Comment by geotmt1** [comment]
Done, everything works. Thanks a lot for your help! Also, please make the set-up instructions more explicit for beginners.

**Comment by kokmok** [comment]
ok I close the issue.

Enjoy !
